#!/bin/sh

PACKAGE="playitGG"
DNAME="playitGG"
INSTALL_DIR="/usr/local/${PACKAGE}"
SSS_SC_DIR="/var/packages/${PACKAGE}/scripts"
PATH="${INSTALL_DIR}/bin:${PATH}"
CONFIG_DIR="/var/packages/${PACKAGE}/etc"

install_log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> /var/log/${PACKAGE}_install.log
}

call_func() {
    FUNC=$1
    shift
    if [ "$(type -t "${FUNC}")" = "function" ]; then
        ${FUNC} "$@"
    fi
}

syno_remove_user() {
    USERNAME=$1
    synouser --del "$USERNAME" 2>&1 | install_log
}

syno_group_create() {
    GROUPNAME=$1
    synogroup --add "$GROUPNAME" 2>&1 | install_log
}

syno_group_remove() {
    GROUPNAME=$1
    synogroup --del "$GROUPNAME" 2>&1 | install_log
}

syno_user_add_to_group() {
    USERNAME=$1
    GROUPNAME=$2
    synogroup --member "$GROUPNAME" "$USERNAME" add 2>&1 | install_log
}

set_syno_permissions() {
    DIRECTORY=$1
    USERNAME=$2
    synoacltool -add "$DIRECTORY" "user:${USERNAME}:rwxpdDaARWcC-" 2>&1 | install_log
}

preinst() {
    install_log "Pre-install script started"
}

postinst() {
    install_log "Post-install script started"
    ln -s ${INSTALL_DIR} /var/packages/${PACKAGE}/target 2>&1 | install_log
}

preuninst() {
    install_log "Pre-uninstall script started"
}

postuninst() {
    install_log "Post-uninstall script started"
    rm -rf ${INSTALL_DIR} 2>&1 | install_log
}

preupgrade() {
    install_log "Pre-upgrade script started"
}

postupgrade() {
    install_log "Post-upgrade script started"
}