PLAYIT_SECRET="c113ce3d302ac279f60912ceae77c31d686179b3462073dc3f71ac6ed84e090f"
no-autoupdate: true
management-diagnostics: @management-diagnostics@
post-quantum: @post-quantum@
edge-ip-version: "@edge-ip-version@"
