#!/bin/sh

PACKAGE_USER="playitgg"
PACKAGE_DIR="/var/packages/playitgg"

# Sprawdzenie wersji DSM
DSM_VERSION=$(get_key_value /etc.defaults/VERSION majorversion)

# Sprawdzenie, czy użytkownik istnieje
if ! id "${PACKAGE_USER}" >/dev/null 2>&1; then
    echo "Tworzenie użytkownika ${PACKAGE_USER}..."
    if [ "${DSM_VERSION}" -ge 7 ]; then
        synouser --add "${PACKAGE_USER}" "SecureRandomPass123!" 0 "" "" > /dev/null
    else
        adduser -h "${PACKAGE_DIR}" -G users -S "${PACKAGE_USER}"
    fi
fi

# Zmiana właściciela i uprawnień katalogu pakietu
chown -R ${PACKAGE_USER}:users ${PACKAGE_DIR}
chmod -R 750 ${PACKAGE_DIR}

exit 0

