#!/bin/sh

# Package name
PACKAGE="playitgg"
# Package specific variables
# Default display name
DNAME="${SYNOPKG_PKGNAME}"
LOG_FILE="${SYNOPKG_PKGVAR}/${SYNOPKG_PKGNAME}.log"
INSTALL_DIR="/var/packages/${PACKAGE}/target"
PID_FILE="${INSTALL_DIR}/playit.pid"
PLAYIT_BIN="${INSTALL_DIR}/bin/playit-linux"

# Start the package
start_daemon() {
    # Check if already running
    if [ -f ${PID_FILE} ] && kill -0 $(cat ${PID_FILE}) > /dev/null 2>&1; then
        echo "${DNAME} is already running"
        exit 0
    fi

    # Start the daemon
    echo "Starting ${DNAME} ..."
    cd ${INSTALL_DIR}
    ${PLAYIT_BIN} > /dev/null 2>&1 & >> ${LOG_FILE}
    echo $! > ${PID_FILE}
}

# Stop the package
stop_daemon() {
    # Check if running
    if [ ! -f ${PID_FILE} ] || ! kill -0 $(cat ${PID_FILE}) > /dev/null 2>&1; then
        echo "${DNAME} is not running"
        exit 0
    fi

    echo "Stopping ${DNAME} ..."
    kill $(cat ${PID_FILE})
    rm -f ${PID_FILE}
}

# Get the status of the package
daemon_status() {
    if [ -f ${PID_FILE} ] && kill -0 $(cat ${PID_FILE}) > /dev/null 2>&1; then
        echo "${DNAME} is running"
        exit 0
    else
        echo "${DNAME} is not running"
        exit 1
    fi
}

# Main script logic
case $1 in
    start)
        start_daemon
        ;;
    stop)
        stop_daemon
        ;;
    status)
        daemon_status
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
        ;;
esac

exit 0

