#!/bin/sh

DAEMON="/var/packages/playitGG/target/bin/playit-linux-amd64"
PIDFILE="/var/run/playitGG.pid"

start_daemon() {
    $DAEMON > /dev/null 2>&1 &
    echo $! > $PIDFILE
}

stop_daemon() {
    [ -f "$PIDFILE" ] && kill $(cat $PIDFILE) && rm -f $PIDFILE
}

status_daemon() {
    [ -f "$PIDFILE" ] && echo "Running" || echo "Stopped"
}

case "$1" in
    start) start_daemon ;;
    stop) stop_daemon ;;
    status) status_daemon ;;
    *) echo "Usage: $0 {start|stop|status}" ;;
esac
exit 0
